### ISSUE TITLE
Remove dead code - validate url

### ISSUE THREAD

**Issue by BradfordMedeiros** [GoogleCloudPlatform/k8s-cluster-bundle#160]
Dead code:
https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/validate/validate_url.go#L25

Maybe a linter could solve this type of problem.

**Comment by Kashomon** [comment]
Ah, that got broken when we migrated from Components to Components + ComponentBuilder. The URL moved to the ComponentBuilder; I forgot to re-add validation for the Component Builder. Want to do that?

**Comment by Kashomon** [comment]
Is this fixed now?
