### ISSUE TITLE
Clarify what part of this repo is the public/library api

### ISSUE THREAD

**Issue by BradfordMedeiros** [GoogleCloudPlatform/k8s-cluster-bundle#161]
We use some of this package internally. 

If we just have a mindset that every public package function/type should not be broken, this makes this code very rigid.  I think we probably want to be limited about what functions and types should be available outside of this repo, and only expose a deliberate subset.    We expose more than we use externally because we need to to allow other functions in this repo to use it. 

For example, commands/find lives as its own package.   It makes AddCommands to available outside of this repo as a public interface, despite being intended for the bundlectl binary.  

As a result, it creates rigidity:  I want to only be concerned with the bundlectl binary, but because it's public and we import this elsewhere, we really can't modify anything public without potentially breaking our internal consumers of it as well. 

Especially being new and not being the one having written the internal usage, this is very hard to reason about.   It would relatively easy to create a convention of "this one package methods will not be broken by consumers of the package"

**Comment by Kashomon** [comment]
> Clarify what part of this repo is the public/library api

My current answer to this question has been: Only the `bundlectl` tool and the types are 'public'.

I'm not opposed to making a clear 'this is the public Go API', but I agree, we'd need a little thought about what that looks like. I think #91 could evolve into that.

> If we just have a mindset that every public package function/type should not be broken, this makes this code very rigid.

I don't assume this at all =). We do use some of this internally on GKE. However, that doesn't matter for the library development here. If we break internal, that's ok, we'll just go fix it when we do a pull.

> I want to only be concerned with the bundlectl binary,

You can make that assumption today =).

**Comment by Kashomon** [comment]
I think the big part of this is a documentation issue. I'll take this on.
