### ISSUE TITLE
Inline is ignored for build 

### ISSUE THREAD

**Issue by BradfordMedeiros** [GoogleCloudPlatform/k8s-cluster-bundle#173]
Inline flag is ignored for build, but not for validate of the same type, at least for some types (for example bundle builder).  

This means validation will fail at build time for the type, and not be caught in validate.

**Comment by Kashomon** [comment]
We should ditch the inline flag now that we have a Build command

**Comment by Kashomon** [comment]
I can take this.

**Comment by Kashomon** [comment]
Accidentally closed this. Still need to clean up some detritus

**Comment by Kashomon** [comment]
I think this can be closed with @BradfordMedeiros's cleanup. Please reopen if you think it needs more work.
