### ISSUE TITLE
Add a command to create objects from object templates

### ISSUE THREAD

**Issue by Kashomon** [GoogleCloudPlatform/k8s-cluster-bundle#248]
We could really use a command to create objects from object templates

```
bundlectl apply -f component.yaml --options-file=foo.yaml
```

or maybe

```
bundlectl render -f component.yaml --options-file=blah.yaml
```

**Comment by Zyqsempai** [comment]
@mamaso Are you working on it?

**Comment by mamaso** [comment]
@Zyqsempai I am not, feel free to take this on

**Comment by Kashomon** [comment]
This should probably use the multi applier in `pkg/options/multi` by default and then allow users to select just a single type (`patch`, `gotmpl`, `multi`, etc.) if they desire. Still not sure what the name of the command should be. Maybe `render ` is right. Maybe it's `apply`, but i worry there's overlap with `kubectl apply`
